LoadTexture("cvfx1", "assets/card/cardvfx1.png")

require("game.card.clock")
require("game.card.crod")
require("game.card.gourd")
require("game.card.grimoire")
require("game.card.tfan")
require("game.card.corolla")
require("game.card.sp_doll")
require("game.card.rblade")
require("game.card.earrow")
require("game.card.archerd")
require("game.card.hfield")
require("game.card.mbend")
require("game.card.mspark")