local M = boss.dialog.New(true)
M.boss = "game.boss.haiji"
require("zinolib.misc")
require("math.additions")
package.loaded["game.boss.portraits"]=nil
require("game.boss.portraits")
---general help!!
---familar(master,x,y,hp,color,transfer rate)
---bullet(img,color,x,y,speed,ang,indes,add)
--boss.dialog.sentence(self,"Satori_6", "left", "", t, h,v,3)
function M:init()
    lstg.player.dialog=true
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    boss.SetUIDisplay(self,false,false,false,false,true,false)
    task.New(self,function()
        local t = 90000
        local h, v = 0.5/2.25, 0.5/2.25
        boss.dialog.sentence(self,"Satori_6", "left", "What's up with all this noise???\nIt feels like all those cards are irradiating thoughts...", t, h,v,3)
        boss.dialog.sentence(self,"Satori_5", "left", "I feel like I want to solve this\nincident just to be able to sleep again...", t, h,v,3)
        boss.dialog.sentence(self,"img_void", "right", "Crap crap crap crap crap crap...", t,h,v,3,5,0,0,230+150+150)
        boss.dialog.sentence(self,"img_void", "right", "I hope no one notices I did all this...", t,h,v,3,5,0,0,230+150+150)
        boss.dialog.sentence(self,"Satori_8", "left", "...Come out at once you!", t, h,v,2)
        task.New(self, function()
            task.MoveTo(0,120,150,MOVE_ACC_DEC)
        end)
        boss.dialog.sentence(self,"Haiji_4", "right", "...oh! Uh....", t, h,v,1)
        boss.dialog.sentence(self,"Haiji_2", "right", "Hiii~~ How can I help you?", t, h,v,1)
        boss.dialog.sentence(self,"Satori_6", "left", "Don't play stupid with me!", t, h,v,2)
        boss.dialog.sentence(self,"Satori_8", "left", "Are you releasing those cards into\nthe wild?", t, h,v,2)
        boss.dialog.sentence(self,"Haiji_4", "right", "ohmygodohmygodohmygodohmygod", t, h,v,3)
        boss.dialog.sentence(self,"Haiji_5", "right", "...no?", t, h,v,4)
        boss.dialog.sentence(self,"Satori_6", "left", "...Are you trying to lie to a satori?", t, h,v,1)
        boss.dialog.sentence(self,"Haiji_6", "right", "...no?", t, h,v,4)
        boss.dialog.sentence(self,"Satori_7", "left", "...I can read minds.", t, h,v,1)
        boss.dialog.sentence(self,"Haiji_4", "right", "........................", t, h,v,3)
        boss.dialog.sentence(self,"Haiji_3", "right", "Girllllll you won't believe\nwhat happened!", t, h,v,1)
        boss.dialog.sentence(self,"Haiji_6", "right", "An extradimentional portal\nappeared and-", t, h,v,1)
        boss.dialog.sentence(self,"Satori_5", "left", "You were smuggling cards and you tripped.", t, h,v,1)
        boss.dialog.sentence(self,"Haiji_6", "right", "That Works I Suppose.", t, h,v,1)
        task.NewNamed(self, "move", function()
            task.MoveTo(200,180,300,MOVE_ACCEL)
        end)
        boss.dialog.sentence(self,"Haiji_2", "right", "So anyways I will be going! Bye!", t, h,v,1)
        boss.dialog.sentence(self,"Satori_8", "left", "Not so fast!!!!", t, h,v,2)
        task.NewNamed(self,"move", function()
        
        end)
        boss.dialog.sentence(self,"Satori_8", "left", "You will clean all of this up!", t, h,v,2)
        task.NewNamed(self, "move", function()
            task.MoveTo(0,120,60,MOVE_ACC_DEC)
        end)
        boss.dialog.sentence(self,"Haiji_8", "right", "Hey! I really have to go!", t, h,v,1)
        boss.dialog.sentence(self,"Satori_6", "left", "Such a headache...\nAnd I'll have to fight her...", t, h,v,3)
        boss.dialog.sentence(self,"Satori_8", "left", "You won't go anywhere!", t, h,v,2)
        boss.dialog.sentence(self,"Haiji_5", "right", "I see where this is going~", t, h,v,1)
        boss.dialog.sentence(self,"Haiji_8", "right", "You'll have to make me! Behold the power\nof my newly-copied danmaku!", t, h,v,1)
        boss.dialog.sentence(self,"Satori_6", "left", "Good grief...", t, h,v,3)
        --task.Wait(1000)
        _del(self,true)
    end)
end

return M